---
#
# Ansible managed
#
repository:
  description: Install stratis and carves pools and filesystems.
  homepage: https://robertdebock.nl/
  topics: stratis, storage, system, ansible, molecule, tox, playbook
