---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    # - namespace="archlinux" image="base"
    - image="centos"
    - image="fedora"
    - image="fedora" tag="rawhide"

matrix:
  allow_failures:
    - env: image="fedora" tag="rawhide"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "bVTIJB78g+VEfJ2m3xK2fzgkQfOgExOqu/XqXfFENtCaTkBk0LPe6yaWn+IuAgq3yyW8NqdTv5HkEEiRlydspiq+qmVmt7x0417lCZeiIKpz/efsfJNWFVwfjm8G9cizIz1FncofxKq3aa0ToZp1kf9R2J0h4ZQoT9tElxvcnXeP2HUYyx/KVGT2Iyazk+Pjc68vXQKZERYDk2x1b3W2AA9+wVWYHkZ6uTAG+FSE8SvYDhRXovk8cEqv+w0k5wl38a2I83hrcp7K2od8m0xp9IA6XbRCIrG0ReGfhKHfQajW6NwPIhdyNGM+WvTGFca8oPi5AHGcnOCW/tnFLyV7Vi+vMol9eWQZa9TJt4VHCvyf4aMfH7mCororPgxckldEb+Y19kYvjNMVgN9xLT/QnNsXimzMNbh8AmNGREwrKgwdNvwKtOKrjKqvUGQt6NnA9p1Y39LWuVjbzudpEaAG8+Mqmww0R9r3+pNnOUH1PYF6FQd4ZGPRKdu3IYeEw/YXBZnSEuI8BsxBhqWy6MiCW3MkLLUvBUcb8oSss3Rxz1OoTwbxre2ptEgudhlHr6Qn/4UxOfJd9jOjCDCZbUNdB10DWU23iluR1HrhkxMT878HGmpz/X2HMCnz7yH95VCg5o4TKAznakfvpuULAlG5R3Qk6R8HQ5LTm0PkccI0zbE="
  email: false
