---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="latest"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - function retry { counter=0 ; until "$@" ; do exit=$? ; counter=$(($counter + 1)) ; if [ $counter -ge 3 ] ; then return $exit ; fi ; done ; return 0; } ; retry tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "vZgTnLppuhnYtZKbTjZ378xxj7JVPIKKIEiezQ1cJZWkzEmG3d1xl9LobSdffLaXATFmH28lT4o+kYRxhtlJH+4IWeAJSM/Dnl91XaPBcRtCLvY8y16/0lV1m27mzB96MDp0OhMw9MgIOwEmMciQZzxqORgNUIQuC+CogUQOvgF8P4rcJFs9IJZcCvPvrrlaSSkCWOCoKWIuAL9pWhe0Dr9WPtUzZEZLGvVsNATKpOj7+JtJa6o/sFOyEQs4f1L8VmqYTIFPGvBOlA+YKrhLFluu7P8AFvxJVYb8epozIFHuyjAAKmYXkfdOpCgV5Wb9C2Pj1/HQXAb6Ggy5KzP6qBjyUPV1IHi26ogYlMHSHPRb0uk/JNTn3UatTS/G3NjFnUN3BkW3J9WdPwiIBY3Ah3roNW1GYfktx183q1BDIFnH0IJzqbc6oc7xPerbdM4TaH5NgJZxNAzWG8XQvRCuy8wkJiUNJ+ZhlqCdfuTrK02oadelhs+BjAU+N1UusGfk7ZMX9phvcCDfyMIJlIEJiOscz1Hxn1GCdcjXak9/cqcMIjH3uPnuSya7nlUb/ZkKpiHzWAh4FPpxSPvz1sPKGEZE8zbfIhX/KAItT+kMznB2hWxyCoWqDbIic6f5mo2rToRiWmsBYlZtfmsLECamGtj9jkXBJaVEU+TsLsn0mbo="
  email: false
