---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="latest"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      - secure: "CJ1dXzD18hA0NAqjt6CeoTAn/zThzHv+UiIAnom58WMrhJrqgwUdU7xe+Te0hXAVrdyfmMA3egQKNEZiY1TnqAZMoRmiJJf9Jiy+GYVE8xd9lFo1QZq6oy5bQhoPL7EtTn6kP6+2ouBBCpQuzysbyozBCGdbtW2//n8PSDa5nZ9Pw6iYHeVaKlfhgwWBSSaIs2jU1HVbg1KwhAYn+3fb2PNCtTs9KkBWKwXvEziih77hrodlUshB12P64QdEKOUKnaKw1pmkGuknbK9iWsiHcGmqequqKWZ8nkP0srrJ3u1cZ2YFxw2BctDWny4gBS0eqEqIwpJfU6yepKsChn0KQTgqyNUblu7T0d85kuvPnBYY7Fnk1QdLcHKEj8pqtiWxMs1NS5o4iy0yE5w5jFspZZYjBpc3+AVUKeI1k645Or46QSZDXfLXOEsPzpKNPY2exAXCMhv0TvSLcfIMJ90t+gb+aNa/Cex3ktK9S1B+25E+/HxQnwx/cQjpQakaxNAmI/WaysHK+K96rrYGWP1srsXhpQl60rbliFxOFtOrPZlp6NPDDDPHrHq1TtThdxzNCq9Ltvg0Or4XBrebbOlMcRLR6SUKdBQ9RLkSHoD1iykd6yfTGHu3GqiHM2UUwmdJgEOGe4wZ2ZXL7Wt9ipv28ZAQR2E1btCY/C6NFmePuh4="
  email: false
