---
# tasks file for stratis
- name: install stratis
  package:
    name: "{{ stratis_packages }}"
    state: present

- name: start and enable stratis
  service:
    name: "{{ stratis_service }}"
    state: started
    enabled: yes

- name: create pools
  command: stratis pool create {{ item.name }} {{ item.devices | join(' ') }}
  args:
    creates: /stratis/{{ item.name }}
  loop: "{{ stratis_pools }}"
  when:
    - stratis_pools is defined
  loop_control:
    label: "{{ item.name }}"

- name: create filesystems
  command: stratis fs create {{ item.pool }} {{ item.name }}
  args:
    creates: /stratis/{{ item.pool }}/{{ item.name }}
  loop: "{{ stratis_filesystems }}"
  when:
    - stratis_filesystems is defined
  loop_control:
    label: "{{ item.name }}"

- name: create mountpoint
  file:
    path: "{{ item.mountpoint }}"
    state: directory
    recurse: yes
    mode: "0755"
  loop: "{{ stratis_mounts }}"
  when:
    - stratis_mounts is defined
  loop_control:
    label: "{{ item.mountpoint }}"

- name: mount filesystems
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: xfs
    state: present
  loop: "{{ stratis_mounts }}"
  when:
    - stratis_mounts is defined
  loop_control:
    label: "{{ item.mountpoint }}"
