---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - robertdebock.bootstrap

  tasks:
    - name: create file
      command: dd if=/dev/zero of={{ item }} bs=512 count=1048576
      args:
        creates: "{{ item }}"
      with_items:
        - device1
        - device2
